### ISSUE TITLE
Does not support UTF-16 or UTF-32

### ISSUE THREAD

**Issue by jbowtie** [tallakt/codepagex#2]
This should be a pretty straightfoward conversion since the character set is the same. I suspect you need to do a binary conversion rather than relying an mapping file though.

**Comment by tallakt** [comment]
I will look into it. One reason it has been left out is that i dont much like these, as they are very confusing (many think these are fixed size codepoints) and rely on endianness. But they should of course be in there. Thanks

**Comment by jbowtie** [comment]
I have a set of test documents you can use here:

https://github.com/jbowtie/ratapotion/tree/master/testdocs

The set includes big and little endian documents with and without byte order marks.

**Comment by jbowtie** [comment]
Looks like `:unicode.characters_to_list` can handle UTF-16 and UTF-32 just fine regardless of endian-ness so you just need to delegate for those encodings.

**Comment by tallakt** [comment]
Hi. I'm going to close this for now. I don't have much personal interest in these encodings. If you wanted to make a pull request wrapping any such erlang functions I would give it serious consideration, otherwise, I might add some docs to recommend using the built in functionality for these encodings.
